### ISSUE TITLE
"Please select and asset account" when creating new transaction. 

### ISSUE THREAD

**Issue by Seemseasy11** [dreautall/waterfly-iii#717]
[![Screenshot_20251210-062558~2.png](https://github.com/user-attachments/assets/2eb5a498-6c70-4fdf-91bf-5899f04f5d4d)

Hello, 

I am on a Pixel 9 pro XL, Android 16, app version F-Droid - 1.1.9.

When creating a new transaction, I set the asset accounts, in the case of this screenshot, (no name) for Source Account and a shared asset account for the Destination Account. The app recognizes that it is a deposit because the little indicator changes to the green arrow. However, when I hit save, the indication at the bottom of the screen to "please select an asset account". If I delete the Destination Account and re-add it, the transaction save accepts. 

I can't seem to create this issue everytime, it seems to be intermittent.

**Comment by dreautall** [comment]
Hi, the account is really labeled "(no name)" and is a normal asset account in FF3?

Would be great if you could somehow replicate the behavior, so far I was unable to do so.

**Comment by pcheynem1520** [comment]
Not sure if I'm having the exact same issue since OP's source account has name oddities, but I have the same error message when I attempt to use a liability account as the source.

<img width="1080" height="2340" alt="Image" src="https://github.com/user-attachments/assets/0153f66d-3a95-4b11-84c5-689e9b78f7f2" />

**Comment by dreautall** [comment]
Did you select the account from the drop-down, or just used autocomplete/typed it in?

**Comment by pcheynem1520** [comment]
When selecting the liability account from the drop-down menu, I get the "Please select an asset account" error. When typed istead of selecting from the menu, the error is "Please fill in the accounts first."

**Comment by dreautall** [comment]
Thanks, I'll check with liability accounts then. I only rarely used them myself, maybe I just always used the Webinterface then. I'll have a look!

**Comment by dreautall** [comment]
sorry for the long wait, should be fixed next release finally!

**Comment by thebiblelover7** [comment]
@dreautall I still get something similar on v1.2.0+6273

Whenever I try to add a withdrawal from a liability, it asks me to fill in the accounts first. It still works on the web interface, but now no longer works on the Waterfly app.

<img width="1080" height="1239" alt="Image" src="https://github.com/user-attachments/assets/c9e72dfa-c1ff-460d-8db5-3701361db2c7" />

**Edit**: I made sure that I selected the account from the dropdown, and it shows me the same error.

**Comment by dreautall** [comment]
You're correct, I just applied the fix for liability accounts - unfortunately debt, mortgage etc. are tracked & listed separately for some reason. I'll expand the fix in #789, sorry for that!

**Comment by thebiblelover7** [comment]
@dreautall No worries, thanks for working on it! I really appreciate your work on this application.
